name: sicomar-2021-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - shapely
  - cartopy
  - geopy
  - pip
  - pip:
    - pandas
    - matplotlib
    - netCDF4
    - xarray
    - branca